Galera, bom dia!
Segue resposta do exercicio 1 de ontem. Tivemos muitos problemas no ambiente de vocês para conectar com o SQL. Isso é recorrente, conseguimos instalar na grande maioria das máquinas. Porém não sei se todos os alunos conseguiram acessar a base de dados. Ontem tentamos também pelo Colab, mas ele não possuia os driver necessários instalados, então pesquisei como fazer a instalação e já disponibilizei o código para voces. É o comando abaixo:

In [ ]:
%%sh
curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list > /etc/apt/sources.list.d/mssql-release.list
sudo apt-get update
sudo ACCEPT_EULA=Y apt-get -q -y install msodbcsql17
sudo pip install pyodbc
sudo pip install sqlalchemy
sudo pip install mysqlclient

In [4]:
import sqlalchemy, pandas as pd,pyodbc
server =  'ec2-23-21-245-38.compute-1.amazonaws.com' #servidor
database = 'FIT_2022' #banco
username = 'aluno' #usuario
password = 'aluno123' #senha
con1 = f"mssql+pyodbc://{username}:{password}@{server}/{database}?driver=ODBC Driver 17 for SQL Server"
engine = sqlalchemy.create_engine(url = con1)
engine.connect()

OperationalError: ignored

In [ ]:
df = pd.read_csv("")

In [ ]:
df = pd.read_sql("industrias",engine)
df

,id,ano,code,nome,tamanho,variavel,valor,unidade,data
0,1,2011,A,"Agriculture, Forestry and Fishing",a_0,Activity unit,46134,COUNT,2022-01-01 00:00:00.000
1,2,2011,A,"Agriculture, Forestry and Fishing",a_0,Rolling mean employees,0,COUNT,2022-01-01 00:00:00.000
2,3,2011,A,"Agriculture, Forestry and Fishing",a_0,Salaries and wages paid,279,DOLLARS(millions),2022-01-01 00:00:00.000
3,4,2011,A,"Agriculture, Forestry and Fishing",a_0,"Sales, government funding, grants and subsidies",8187,DOLLARS(millions),2022-01-01 00:00:00.000
4,5,2011,A,"Agriculture, Forestry and Fishing",a_0,Total income,8866,DOLLARS(millions),2022-01-01 00:00:00.000
...,...,...,...,...,...,...,...,...,...
995,996,2011,M,"Professional, Scientific and Technical Services",c_6-9,Total expenditure,1718,DOLLARS(millions),2022-08-31 19:27:51.490
996,997,2011,M,"Professional, Scientific and Technical Services",c_6-9,Operating profit before tax,255,DOLLARS(millions),2022-08-31 19:27:51.490
997,998,2011,M,"Professional, Scientific and Technical Services",c_6-9,Total assets,2696,DOLLARS(millions),2022-08-31 19:27:51.490
998,999,2011,M,"Professional, Scientific and Technical Services",c_6-9,Fixed tangible assets,156,DOLLARS(millions),2022-08-31 19:27:51.490
999,1000,2011,M,"Professional, Scientific and Technical Services",d_10-19,Activity unit,1416,COUNT,2022-08-31 19:27:51.490

In [ ]:
#Conectando com o banco de dados 
#Reparem que agora o driver não é mais SQL SERVER e sim ODBC Driver 17 for SQL Server
import sqlalchemy, pandas as pd,pyodbc
server =  'database-2.cpbnkeufuawz.us-east-1.rds.amazonaws.com'
database = 'FIT_2022'
username = 'aluno'
password = 'aluno123'
#engine = create_engine("mysql:///?User=myUser&;Password=myPassword&Database=NorthWind&Server=myServer&Port=3306")
con1 = f'mysql://{username}:{password}@{server}/{database}'
engine_mysql = sqlalchemy.create_engine(con1)
engine_mysql.connect()

In [ ]:
engine_mysql.execute("create database FIT_2022")

In [ ]:
df.to_sql("industrias",engine_mysql)

In [ ]:
df = pd.read_sql("select * from industrias",con = engine_mysql)
df

,index,id,ano,code,nome,tamanho,variavel,valor,unidade,data
0,0,1,2011,A,"Agriculture, Forestry and Fishing",a_0,Activity unit,46134,COUNT,2022-01-01 00:00:00
1,1,2,2011,A,"Agriculture, Forestry and Fishing",a_0,Rolling mean employees,0,COUNT,2022-01-01 00:00:00
2,2,3,2011,A,"Agriculture, Forestry and Fishing",a_0,Salaries and wages paid,279,DOLLARS(millions),2022-01-01 00:00:00
3,3,4,2011,A,"Agriculture, Forestry and Fishing",a_0,"Sales, government funding, grants and subsidies",8187,DOLLARS(millions),2022-01-01 00:00:00
4,4,5,2011,A,"Agriculture, Forestry and Fishing",a_0,Total income,8866,DOLLARS(millions),2022-01-01 00:00:00
...,...,...,...,...,...,...,...,...,...,...
995,995,996,2011,M,"Professional, Scientific and Technical Services",c_6-9,Total expenditure,1718,DOLLARS(millions),2022-08-31 19:27:51
996,996,997,2011,M,"Professional, Scientific and Technical Services",c_6-9,Operating profit before tax,255,DOLLARS(millions),2022-08-31 19:27:51
997,997,998,2011,M,"Professional, Scientific and Technical Services",c_6-9,Total assets,2696,DOLLARS(millions),2022-08-31 19:27:51
998,998,999,2011,M,"Professional, Scientific and Technical Services",c_6-9,Fixed tangible assets,156,DOLLARS(millions),2022-08-31 19:27:51
999,999,1000,2011,M,"Professional, Scientific and Technical Services",d_10-19,Activity unit,1416,COUNT,2022-08-31 19:27:51

In [ ]:
query = "SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES" 
df = pd.read_sql(query,con = engine)
df

                 TABLE_NAME
0  FUNCIONARIO_2021_edu.sql
1      funcionario_2021.csv

In [ ]:
query = "SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES" 
df = pd.read_sql(query,con = engine)
df
for a,i in df.iterrows():
  tabela = i['TABLE_NAME']
  try:
    
    engine.execute(f" drop table  {tabela}")
  except:
    print(tabela)

FUNCIONARIO_2021_edu.sql
funcionario_2021.csv

In [ ]:
engine.

AttributeError: ignored

In [ ]:
#Aqui estou criando um dataframe para cada tabela (FUNCIONARIO,PRODUTO,SERVICO)
df_funcionario = pd.read_sql(sql ="SELECT * FROM FUNCIONARIO",con=engine)
df_produto = pd.read_sql(sql ="SELECT * FROM PRODUTO ",con=engine)
df_servico = pd.read_sql(sql ="SELECT * FROM SERVICO",con=engine)

In [ ]:
#Para cada dataframe, estou salvando um arquivo no repositório sample_data (FUNCIONARIO,PRODUTO,SERVICO)
#Para acessar esse dado, só ir na aba ao lado esquerdo e clicar na "pasta"
df_funcionario.to_csv("sample_data/funcionario.csv",index=False, line_terminator='\n')
df_produto.to_csv("sample_data/produto.csv",index=False, line_terminator='\n')
df_servico.to_csv("sample_data/servico.csv",index=False, line_terminator='\n')
df_servico.to_csv("sample_data/cliente.csv",index=False, line_terminator='\n')

In [ ]:
#Agora vamos ler os csvs gerados anteriormente para inserir do banco de dados dataeng_stage:
df_servico = pd.read_csv("/content/clientes.csv",delimiter = ';', encoding = "ISO-8859-1")
df_funcionario= pd.read_csv("/content/funcionario.csv",delimiter = ';')
df_produto = pd.read_csv("/content/produto.csv",delimiter = ';')
df_servico = pd.read_csv("/content/servico.csv",delimiter = ';')

In [ ]:
df_servico.to_sql("servico",engine,if_exists="append")
df_funcionario.to_sql("funcionario",engine,if_exists="append")
df_produto.to_sql("produto",engine,if_exists="append")
df_servico.to_sql("servico",engine,if_exists="append")

In [ ]:
#Gravando no banco de dados
df_funcionario_stage.to_sql("funcionario_stage",engine2,if_exists="append")
df_produto_stage.to_sql("produto_stage",engine2,if_exists="append")
df_servico_stage.to_sql("servico_stage",engine2,if_exists="append")

In [ ]:
#Gravando no banco de dados
df_funcionario_stage.to_sql("funcionario_stage",engine2,if_exists="append")
df_produto_stage.to_sql("produto_stage",engine2,if_exists="append")
df_servico_stage.to_sql("servico_stage",engine2,if_exists="append")

In [ ]:
df2.to_sql("funcionario_2021", con=engine, if_exists="replace")